#frontend CI/Cd pipeline

name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - dev-githubactions
  pull_request:
    branches:
      - dev-githubactions
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
